// GitHub Wiki Publisher for RepoLens
//
// Publishes rendered documentation to a GitHub repository's wiki.
// The wiki is a separate git repo at {repo-url}.wiki.git.
//
// Environment Variables:
// - GITHUB_TOKEN: Personal access token or Actions token (required)
// - GITHUB_REPOSITORY: owner/repo (auto-set in Actions, or detected from git remote)
//
// Config (.repolens.yml):
//   github_wiki:
//     branches: [main]           # Optional branch filter
//     sidebar: true              # Generate _Sidebar.md (default: true)
//     footer: true               # Generate _Footer.md (default: true)

import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { info, warn } from "../utils/logger.js";
import { getCurrentBranch, getBranchQualifiedTitle, normalizeBranchName } from "../utils/branch.js";

const PAGE_ORDER = [
  "executive_summary",
  "system_overview",
  "business_domains",
  "architecture_overview",
  "module_catalog",
  "route_map",
  "api_surface",
  "data_flows",
  "change_impact",
  "system_map",
  "developer_onboarding",
  "graphql_schema",
  "type_graph",
  "dependency_graph",
  "architecture_drift",
  "arch_diff",
];

const PAGE_TITLES = {
  executive_summary: "Executive Summary",
  system_overview: "System Overview",
  business_domains: "Business Domains",
  architecture_overview: "Architecture Overview",
  module_catalog: "Module Catalog",
  route_map: "Route Map",
  api_surface: "API Surface",
  data_flows: "Data Flows",
  change_impact: "Change Impact",
  system_map: "System Map",
  developer_onboarding: "Developer Onboarding",
  graphql_schema: "GraphQL Schema",
  type_graph: "Type Graph",
  dependency_graph: "Dependency Graph",
  architecture_drift: "Architecture Drift",
  arch_diff: "Architecture Diff",
};

/**
 * Detect the GitHub repository (owner/repo) from environment or git remote.
 */
function detectGitHubRepo() {
  // GitHub Actions sets this automatically
  if (process.env.GITHUB_REPOSITORY) {
    return process.env.GITHUB_REPOSITORY;
  }

  // Detect from git remote
  try {
    const remoteUrl = execSync("git remote get-url origin", {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "ignore"],
    }).trim();

    // HTTPS: https://github.com/owner/repo.git
    const httpsMatch = remoteUrl.match(/github\.com\/([^/]+\/[^/.]+)/);
    if (httpsMatch) {
      return httpsMatch[1];
    }

    // SSH: git@github.com:owner/repo.git
    const sshMatch = remoteUrl.match(/github\.com:([^/]+\/[^/.]+)/);
    if (sshMatch) {
      return sshMatch[1];
    }
  } catch {
    // git command failed
  }

  return null;
}

/**
 * Build the authenticated wiki clone URL.
 */
function buildWikiCloneUrl(repo, token) {
  return `https://x-access-token:${token}@github.com/${repo}.wiki.git`;
}

/**
 * Convert a page key to a wiki-safe filename.
 * GitHub Wiki filenames become the page URLs.
 */
function pageFileName(key) {
  const title = PAGE_TITLES[key] || key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
  // GitHub Wiki uses filenames as page titles, dashes for URL slugs
  return title.replace(/\s+/g, "-") + ".md";
}

/**
 * Generate _Sidebar.md with links to all pages.
 */
function generateSidebar(pageKeys, projectName, branch) {
  const title = getBranchQualifiedTitle(projectName, branch);
  const lines = [`### ${title}`, ""];

  for (const key of PAGE_ORDER) {
    if (pageKeys.includes(key)) {
      const displayTitle = PAGE_TITLES[key] || key;
      const wikiPageName = pageFileName(key).replace(/\.md$/, "");
      lines.push(`- [[${displayTitle}|${wikiPageName}]]`);
    }
  }

  // Include any custom/plugin pages not in the standard order
  for (const key of pageKeys) {
    if (!PAGE_ORDER.includes(key)) {
      const displayTitle = key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
      const wikiPageName = pageFileName(key).replace(/\.md$/, "");
      lines.push(`- [[${displayTitle}|${wikiPageName}]]`);
    }
  }

  lines.push("", "---", `*Generated by [RepoLens](https://github.com/CHAPIBUNNY/repolens)*`);
  return lines.join("\n");
}

/**
 * Generate _Footer.md.
 */
function generateFooter(branch) {
  const branchNote = branch !== "main" && branch !== "master"
    ? ` from branch \`${branch}\``
    : "";
  return `---\n*Documentation generated by [RepoLens](https://github.com/CHAPIBUNNY/repolens)${branchNote}*`;
}

/**
 * Run a git command in the specified directory.
 * Token is never exposed in error output.
 */
function git(args, cwd) {
  try {
    return execSync(`git ${args}`, {
      cwd,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
      env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
    });
  } catch (err) {
    // Sanitize any token from error messages
    const sanitized = (err.stderr || err.message || "").replace(
      /x-access-token:[^\s@]+/g,
      "x-access-token:***"
    );
    throw new Error(`Git command failed: git ${args.split(" ")[0]} — ${sanitized}`);
  }
}

/**
 * Publish rendered pages to GitHub Wiki.
 */
export async function publishToGitHubWiki(cfg, renderedPages) {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      "Missing GITHUB_TOKEN. Required for GitHub Wiki publishing.\n" +
      "In GitHub Actions, this is available as ${{ secrets.GITHUB_TOKEN }}.\n" +
      "Locally, create a PAT with repo scope: https://github.com/settings/tokens"
    );
  }

  const repo = detectGitHubRepo();
  if (!repo) {
    throw new Error(
      "Could not detect GitHub repository. Set GITHUB_REPOSITORY=owner/repo\n" +
      "or ensure git remote 'origin' points to a GitHub URL."
    );
  }

  const branch = getCurrentBranch();
  const wikiConfig = cfg.github_wiki || {};
  const includeSidebar = wikiConfig.sidebar !== false;
  const includeFooter = wikiConfig.footer !== false;
  const projectName = cfg.project?.name || repo.split("/")[1] || "RepoLens";

  // Clone wiki into a temp directory
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "repolens-wiki-"));

  try {
    const cloneUrl = buildWikiCloneUrl(repo, token);

    // Try to clone; if wiki doesn't exist yet, initialize an empty repo
    try {
      git(`clone --depth 1 ${cloneUrl} .`, tmpDir);
    } catch {
      warn("Wiki repository not found — initializing. Enable the wiki tab in GitHub repo settings.");
      git("init", tmpDir);
      git(`remote add origin ${cloneUrl}`, tmpDir);
    }

    // Write Home.md (index page)
    const homeLines = [
      `# ${getBranchQualifiedTitle(projectName + " Documentation", branch)}`,
      "",
      `> Auto-generated architecture documentation by [RepoLens](https://github.com/CHAPIBUNNY/repolens)`,
      "",
      "## Pages",
      "",
    ];

    const pageKeys = Object.keys(renderedPages);
    for (const key of PAGE_ORDER) {
      if (pageKeys.includes(key)) {
        const displayTitle = PAGE_TITLES[key] || key;
        const wikiPageName = pageFileName(key).replace(/\.md$/, "");
        homeLines.push(`- [[${displayTitle}|${wikiPageName}]]`);
      }
    }
    for (const key of pageKeys) {
      if (!PAGE_ORDER.includes(key)) {
        const displayTitle = key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
        const wikiPageName = pageFileName(key).replace(/\.md$/, "");
        homeLines.push(`- [[${displayTitle}|${wikiPageName}]]`);
      }
    }

    await fs.writeFile(path.join(tmpDir, "Home.md"), homeLines.join("\n"), "utf8");

    // Write each rendered page
    for (const [key, markdown] of Object.entries(renderedPages)) {
      const fileName = pageFileName(key);
      await fs.writeFile(path.join(tmpDir, fileName), markdown, "utf8");
    }

    // Generate sidebar
    if (includeSidebar) {
      const sidebar = generateSidebar(pageKeys, projectName, branch);
      await fs.writeFile(path.join(tmpDir, "_Sidebar.md"), sidebar, "utf8");
    }

    // Generate footer
    if (includeFooter) {
      const footer = generateFooter(branch);
      await fs.writeFile(path.join(tmpDir, "_Footer.md"), footer, "utf8");
    }

    // Stage, commit, push
    git("config user.name \"RepoLens Bot\"", tmpDir);
    git("config user.email \"repolens@users.noreply.github.com\"", tmpDir);
    git("add -A", tmpDir);

    // Check if there are changes to commit
    try {
      execSync("git diff --cached --quiet", { cwd: tmpDir, stdio: "pipe" });
      info("GitHub Wiki is already up to date — no changes to push.");
      return;
    } catch {
      // There are staged changes — continue to commit
    }

    const branchLabel = branch !== "main" && branch !== "master" ? ` [${branch}]` : "";
    const commitMsg = `docs: update RepoLens documentation${branchLabel}`;
    git(`commit -m "${commitMsg}"`, tmpDir);

    git("push origin HEAD", tmpDir);
    info(`GitHub Wiki published: https://github.com/${repo}/wiki`);

  } finally {
    // Clean up temp directory
    await fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * Check if GitHub Wiki publishing secrets are available.
 */
export function hasGitHubWikiSecrets() {
  return !!process.env.GITHUB_TOKEN;
}
