import { execSync } from "node:child_process";
import { log } from "../utils/logger.js";
import { fetchWithRetry } from "../utils/retry.js";

function safe(text) {
  return String(text || "").trim();
}

function buildBody(diff) {
  const lines = [
    "## RepoLens — Architecture Summary",
    "",
    `**Added files:** ${diff.added.length}`,
    `**Removed files:** ${diff.removed.length}`,
    `**Modified files:** ${diff.modified.length}`,
    `**Added routes:** ${diff.addedRoutes.length}`,
    `**Removed routes:** ${diff.removedRoutes.length}`,
    `**Impacted modules:** ${diff.impactedModules.length}`,
    ""
  ];

  if (diff.addedRoutes.length) {
    lines.push("### Added routes", "");
    for (const route of diff.addedRoutes.slice(0, 10)) {
      lines.push(`- \`${route}\``);
    }
    lines.push("");
  }

  if (diff.removedRoutes.length) {
    lines.push("### Removed routes", "");
    for (const route of diff.removedRoutes.slice(0, 10)) {
      lines.push(`- \`${route}\``);
    }
    lines.push("");
  }

  if (diff.impactedModules.length) {
    lines.push("### Impacted modules", "");
    for (const module of diff.impactedModules.slice(0, 12)) {
      lines.push(`- \`${module}\``);
    }
    lines.push("");
  }

  lines.push("_Generated by RepoLens_");
  return lines.join("\n");
}

async function githubRequest(method, url, body) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;

  if (!token) throw new Error("Missing GITHUB_TOKEN");
  if (!repo) throw new Error("Missing GITHUB_REPOSITORY");

  const res = await fetchWithRetry(`https://api.github.com${url}`, {
    method,
    headers: {
      "Authorization": `Bearer ${token}`,
      "Accept": "application/vnd.github+json",
      "Content-Type": "application/json",
      "User-Agent": "RepoLens"
    },
    body: body ? JSON.stringify(body) : undefined
  }, {
    retries: 3,
    baseDelayMs: 500,
    maxDelayMs: 4000,
    label: `GitHub ${method} ${url}`
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API error ${res.status}: ${text}`);
  }

  return await res.json();
}

async function findExistingRepoLensComment(owner, repo, issueNumber) {
  const comments = await githubRequest(
    "GET",
    `/repos/${owner}/${repo}/issues/${issueNumber}/comments`
  );

  return comments.find((c) =>
    typeof c.body === "string" && c.body.includes("## RepoLens — Architecture Summary")
  );
}

export async function upsertPrComment(diff) {
  const eventName = process.env.GITHUB_EVENT_NAME;
  if (eventName !== "pull_request") {
    log("GITHUB_EVENT_NAME is not 'pull_request', skipping PR comment.");
    return;
  }

  const repoFull = process.env.GITHUB_REPOSITORY;
  const prNumber = process.env.GITHUB_REF_NAME
    ? undefined
    : undefined;

  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (!eventPath) throw new Error("Missing GITHUB_EVENT_PATH");

  const fs = await import("node:fs/promises");
  const raw = await fs.readFile(eventPath, "utf8");
  const event = JSON.parse(raw);

  const issueNumber = event?.pull_request?.number;
  if (!issueNumber) {
    log("No PR number found, skipping PR comment.");
    return;
  }

  const [owner, repo] = repoFull.split("/");
  const body = buildBody(diff);

  const existing = await findExistingRepoLensComment(owner, repo, issueNumber);

  if (existing) {
    await githubRequest(
      "PATCH",
      `/repos/${owner}/${repo}/issues/comments/${existing.id}`,
      { body }
    );
    log(`Updated existing PR comment ${existing.id}`);
    return;
  }

  const created = await githubRequest(
    "POST",
    `/repos/${owner}/${repo}/issues/${issueNumber}/comments`,
    { body }
  );

  log(`Created PR comment ${created.id}`);
}// update existing PR comment test
